# .github/workflows/deploy.yml
name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server using HTTPS
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PATH: /mnt/web301/e3/49/512373149/htdocs
          REPO_URL: https://github.com/nick558234/strato.git
        run: |
          # Set up HTTPS credentials
          git config --global credential.helper store
          echo "https://${GITHUB_TOKEN}:@github.com" > ~/.git-credentials
          
          # Connect to the server and pull the latest changes using HTTPS
          ssh $SERVER_USER@$SERVER_HOST "
            cd $SERVER_PATH &&
            git pull $REPO_URL main
          "
